name: Release change namespace
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

env:
  NODE_VERSION: '14.x'


defaults:
  run:
    working-directory: ./change-namespace

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yeapai'
      - name: bump version
        run: npm version ${{ github.event.inputs.tag }} --allow-same-version
      - name: Install dependencies and build extension
        run: |
          npm ci
          npm run build
      - name: Create traball from package
        run: npm pack
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.tag }}
          draft: false
          prerelease: true
          files: |
            k8slens-change-namespace-${{ steps.package-version.outputs.current-version}}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
